services:
  db-console:
    build: .
    container_name: db-console
    restart: unless-stopped
    ports:
      - "8090:8090"
    environment:
      DB_ROOT: /data
      CORS_ORIGINS: http://localhost:8090
      PORT: 8090
    volumes:
      - ./data:/data
